### PR TITLE
#3 Create a Github PR template

### PR DESCRIPTION
**Pull request by theaderonkeadebisi**
## What does this PR do?

Provides a PR description template for every new pull request

## Description of Task to be completed

We need to have a structured framework to perfectly describe new pull requests. This template helps PRs to follow a convention and also to avoid painfully copying the PR template every single time a new PR is raised.

## How should this be manually tested?

Verify that the pull request template file exists in the branch and is in the correct location. From the task instructions, the pull request template should be in a .github folder in the root directory and named PULL_REQUEST_TEMPLATE.md.

## Any background context you want to provide?

After this pull request is merged, whenever a new pull request is raised, the template will be in the pull request description by default.

## What are the relevant GitHub issues?

#3 

## Screenshot

Finishes #3

### CODE REVIEW

**Review by SageKyle — APPROVED** [review]
looks good.

**Review by ebenezerdon — CHANGES_REQUESTED** [review]
@theaderonkeadebisi your pull request does not follow the convention you just worked on.

Study the wiki again.

Looks like you created a new issue for this when there's already an existing one assigned to you. Reach out to me on the Discord server if you need any help.

**Review by ebenezerdon — APPROVED** [review]

**Comment by ebenezerdon** [comment]
Congrats on getting your first pull request merged, @theaderonkeadebisi! You've done a great job!

**Comment by theaderonkeadebisi** [comment]
> Congrats on getting your first pull request merged, @theaderonkeadebisi! You've done a great job!

Finally! Thank you.

**Pull request merged**
