### PR TITLE
#05 Setup ESLint

### PR DESCRIPTION
**Pull request by SageKyle**
#### What does this PR do?

Integrates ESLint with Airbnb JS style guide for maintaining code quality and ensuring consistency across the team

#### Description of Task to be completed?

- initialize package.json
- install ESLint as a dev dependency
- install the Airbnb JS style guide config with its peer dependencies
- create a `.eslintrc.json` file for lint configuration
- update rules in `.eslintrc.json` to ignore linebreaks formatting
- update rules in `.eslintrc.json` to enforce single quotes with severity of 1 (warn)
- update rules in `.eslintrc.json` to enforce no unnecessary semicolons with severity of 1 (warn)
- add lint script in `package.json`

#### How should this be manually tested?

1. clone the repository
2. switch to `workflow/05/setup-eslint` branch
3. upon running `npm install` in the command line, all project dependencies should be installed in the local dev environment
4. upon running `npm run lint`, ESLint should run and report any linting errors based on the rules set in the `.eslintrc.json` file
  - the following error should be displayed in the console:
   > warning  Unexpected console statement  no-console

  the error is due to the `console.log` currently in the `index,js`. The linter has been configured to throw a warning on each `console.log` in the JS file.

#### Any background context you want to provide?

Integrating ESLint into the project is crucial for maintaining code quality, ensuring consistency across the team, catching errors early, and enforcing JavaScript best practices. Its integration into the build process further ensures that only quality code gets deployed by throwing an error when the code does not meet the standard.

#### What are the relevant GitHub Issues?

#5 

#### Screenshots (if appropriate)

new rules - eslint

#### Questions:

None

### CODE REVIEW

**Comment by ebenezerdon** [comment]
@SageKyle looks like you pushed node_modules along with your branch. Fix this and add a `.gitignore` file with node_modules ignored so that you don't mistakenly do this again.

**Review by ebenezerdon — CHANGES_REQUESTED** [review]
@SageKyle looks like you pushed node_modules along with your branch. Fix this and add a .gitignore file with node_modules ignored so that you don't mistakenly do this again.

**Comment by ebenezerdon** [comment]
@SageKyle also study the project wiki for Pull request creation

**Comment by SageKyle** [comment]
> @SageKyle also study the project wiki for Pull request creation

I will close this PR now in order to work on this.

**Review by JUNNY12 — CHANGES_REQUESTED** [review]
@SageKyle After running npm run lint , I am getting this error "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style".  You might need to fix that.

Screenshot (40)

**Comment by lambeboluwatife** [comment]
@SageKyle I ran npm lint and got 2 errors and a warning as seen below. If it's an error from my end, how do I fix it?
Screenshot (229)

**Comment by SageKyle** [comment]
> @SageKyle After running npm run lint , I am getting this error "Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style". You might need to fix that.
> 
> Screenshot (40)

Yes I'm aware of this error. To fix this we'll need to configure VScode settings for the project, I'd like to clarify from @ebenezerdon if I should do that as part of this PR or a separate one.

**Comment by ebenezerdon** [comment]
> > @SageKyle After running npm run lint , I am getting this error "Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style". You might need to fix that.
> > Screenshot (40)
> 
> Yes I'm aware of this error. To fix this we'll need to configure VScode settings for the project, I'd like to clarify from @ebenezerdon if I should do that as part of this PR or a separate one.

Yes, you can do it as part of this PR. Mention it in your PR description.

**Comment by SageKyle** [comment]
Hello @JUNNY12 and @lambeboluwatife I have made some changes to the Pull Request, please check it out again.

**Comment by lambeboluwatife** [comment]
> Hello @JUNNY12 and @lambeboluwatife I have made some changes to the Pull Request, please check it out again.

okay, will do

**Comment by lambeboluwatife** [comment]
@SageKyle I got this warning:
Screenshot (230)

**Review by JUNNY12 — CHANGES_REQUESTED** [review]
@SageKyle after reviewing your changes I think this PR is ready for merge unless @ebenezerdon still have further comments. And one more thing make sure to pull from the upstream to stay updated.

Screenshot (41)

**Comment by lambeboluwatife** [comment]
> @SageKyle after reviewing your changes I think this PR is ready for merge unless @ebenezerdon still have further comments. And one more thing make sure to pull from the upstream to stay updated.
> 
> Screenshot (41)

@JUNNY12 Does the warning means the eslint is working or what?

**Comment by SageKyle** [comment]
@ebenezerdon I have made the changes as you requested.

**Review by ebenezerdon — APPROVED** [review]
Well done, Paul

**Pull request merged**
